import { promises as fs } from 'node:fs'
import { dirname } from 'node:path'
import { test, expect, chooseOpen, chooseSave, chooseChanges } from './fixtures'

test('editar, título, negrita, deshacer, guardar y reabrir desde disco', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('nota.md')
  await fs.mkdir(dirname(path), { recursive: true })
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await editor.fill('Una idea que merece espacio')
  await editor.press('Control+A')
  await page.getByRole('button', { name: 'Negrita', exact: true }).click()
  await expect(editor.locator('strong')).toHaveText('Una idea que merece espacio')
  await page.getByRole('button', { name: 'Deshacer', exact: true }).click()
  await expect(editor.locator('strong')).toHaveCount(0)
  await page.getByRole('button', { name: 'Rehacer', exact: true }).click()
  await expect(editor.locator('strong')).toHaveCount(1)
  await page.getByRole('combobox', { name: 'Tipo de bloque' }).click()
  await page.getByRole('option', { name: 'Título 1', exact: false }).click()
  await expect(editor.locator('h1 strong')).toHaveText('Una idea que merece espacio')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(editor).toBeFocused()
  await editor.press('End')
  await expect.poll(() => editor.evaluate(() => globalThis.getSelection()?.isCollapsed)).toBe(true)
  await editor.press('Enter')
  await expect(editor.locator('h1 strong')).toHaveText('Una idea que merece espacio')
  await page.getByRole('combobox', { name: 'Tipo de bloque' }).click()
  await page.getByRole('option', { name: 'Párrafo', exact: false }).click()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(editor).toBeFocused()
  await editor.press('Control+B')
  await page.keyboard.insertText('Escribir con calma. Revisar y dar forma a lo importante.')
  await expect(editor.locator('h1 strong')).toHaveText('Una idea que merece espacio')
  await chooseSave(application, path)
  await page.keyboard.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  const saved = await fs.readFile(path, 'utf8')
  expect(saved).toContain('# **Una idea que merece espacio**')
  expect(saved).toContain('Escribir con calma.')
  await editor.press('End')
  await page.keyboard.insertText(' Edición pendiente.')
  await chooseChanges(application, 1)
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(editor.locator('h1 strong')).toHaveText('Una idea que merece espacio')
  await expect(editor).not.toContainText('Edición pendiente.')
  await expect(page.getByRole('button', { name: 'Deshacer', exact: true })).toBeDisabled()
  expect(await fs.readFile(path, 'utf8')).toBe(saved)
  await page.screenshot({ path: testInfo.outputPath('editor-1000.png') })
  const window = await application.browserWindow(page)
  await window.evaluate((win) => win.setSize(420, 700))
  await expect.poll(() => page.evaluate(() => innerWidth)).toBeLessThanOrEqual(420)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  for (const name of ['Abrir', 'Guardar', 'Negrita', 'Cursiva', 'Cita', 'Rehacer']) {
    const box = await page.getByRole('button', { name, exact: true }).boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(await page.evaluate(() => innerWidth))
    expect(box!.y).toBeGreaterThanOrEqual(32)
  }
  await page.screenshot({ path: testInfo.outputPath('editor-420.png') })
})

test('cancelar guardar, abrir y cerrar conserva los cambios; guardar al cerrar persiste', async ({ application, editorPage: page }, testInfo) => {
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await editor.fill('Pendiente de guardar')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(editor).toHaveText('Pendiente de guardar')
  const nativeWindow = await application.browserWindow(page)
  await nativeWindow.evaluate((win) => win.close())
  await expect(editor).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.documents.current().then(doc => doc.dirty))).toBe(true)
  const path = testInfo.outputPath('al-cerrar.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await chooseChanges(application, 0)
  await chooseSave(application, path)
  const closed = application.waitForEvent('close')
  await nativeWindow.evaluate((win) => win.close())
  await closed
  expect(await fs.readFile(path, 'utf8')).toContain('Pendiente de guardar')
})

test('cambios externos bloquean sobrescritura y permiten guardar otra copia', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('externo.md')
  const copy = testInfo.outputPath('copia.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, '# Original\n\nTexto inicial.\n')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await expect(editor.locator('h1')).toHaveText('Original')
  await editor.press('Control+End')
  await page.keyboard.insertText(' Cambio en hiloo.')
  await fs.writeFile(path, '# Cambio externo\n')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('cambió fuera de hiloo')
  expect(await fs.readFile(path, 'utf8')).toBe('# Cambio externo\n')
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
  await chooseSave(application, copy)
  await page.keyboard.press('Control+Shift+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(copy, 'utf8')).toContain('Cambio en hiloo.')
  expect(await fs.readFile(path, 'utf8')).toBe('# Cambio externo\n')
})

test('original sin editar conserva bytes, BOM y CRLF; formatos no admitidos no sustituyen documento', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('original.md')
  await fs.mkdir(dirname(path), { recursive: true })
  const bytes = Buffer.from('\uFEFFTítulo\r\n======\r\n\r\nUn texto con __énfasis fuerte__.\r\n')
  await fs.writeFile(path, bytes)
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await expect(editor.locator('h1')).toHaveText('Título')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  expect(await fs.readFile(path)).toEqual(bytes)
  await editor.press('Control+End')
  await page.keyboard.insertText(' Cambio temporal.')
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
  await page.keyboard.press('Control+Z')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  expect(await fs.readFile(path)).toEqual(bytes)
  for (const [name, content] of Object.entries({ html: '<script>alert(1)</script>', metadata: '---\ntitle: secreto\n---\nTexto', protocol: '[enlace](javascript:alert%281%29)', imageProtocol: '![imagen](javascript:alert%281%29)' })) {
    const unsupported = testInfo.outputPath(`${name}.md`)
    await fs.writeFile(unsupported, content)
    await chooseOpen(application, unsupported)
    await page.getByRole('button', { name: 'Abrir', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('todavía no admite')
    await expect(editor.locator('h1')).toHaveText('Título')
    expect(await fs.readFile(unsupported, 'utf8')).toBe(content)
  }
})

test('listas, cursiva, cita, enlaces sin navegación y validación de IPC', async ({ application, editorPage: page }, testInfo) => {
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await editor.fill('Un elemento')
  await editor.press('Control+A')
  await page.getByRole('button', { name: 'Cursiva', exact: true }).click()
  await page.getByRole('button', { name: 'Lista con viñetas', exact: true }).click()
  await expect(editor.locator('ul li em')).toHaveText('Un elemento')
  await page.getByRole('button', { name: 'Lista con viñetas', exact: true }).click()
  await expect(editor.locator('ul')).toHaveCount(0)
  await page.getByRole('button', { name: 'Lista numerada', exact: true }).click()
  await expect(editor.locator('ol li')).toHaveCount(1)
  await page.getByRole('button', { name: 'Lista numerada', exact: true }).click()
  await page.getByRole('button', { name: 'Cita', exact: true }).click()
  await expect(editor.locator('blockquote')).toContainText('Un elemento')
  const result = await page.evaluate(() => window.documents.update('id-inválido', 'sobrescritura'))
  expect(result.status).toBe('error')
  const path = testInfo.outputPath('enlaces.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, '[Referencia](https://example.com)\n')
  await chooseChanges(application, 1)
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(editor.locator('a')).toHaveText('Referencia')
  const url = page.url()
  await editor.locator('a').click()
  expect(page.url()).toBe(url)
  expect(application.windows()).toHaveLength(1)
})

test('guardar antes de abrir y cancelar el selector mantiene el documento guardado', async ({ application, editorPage: page }, testInfo) => {
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  const path = testInfo.outputPath('antes-de-abrir.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await editor.fill('Conservar antes de abrir')
  await chooseChanges(application, 0)
  await chooseSave(application, path)
  await chooseOpen(application)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await expect(editor).toHaveText('Conservar antes de abrir')
  expect(await fs.readFile(path, 'utf8')).toContain('Conservar antes de abrir')
  await editor.press('Control+End')
  await page.keyboard.insertText(' y seguir editando.')
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
})

test('atajos de título, párrafo y lista numerada corresponden a las herramientas', async ({ editorPage: page }) => {
  const editor = page.getByRole('textbox')
  await editor.fill('Un bloque')
  await editor.press('Control+A')
  await editor.press('Control+Alt+1')
  await expect(editor.locator('h1')).toHaveText('Un bloque')
  await editor.press('Control+Alt+0')
  await expect(editor.locator('h1')).toHaveCount(0)
  await expect(editor.locator('p')).toHaveText('Un bloque')
  await editor.press('Control+Alt+7')
  await expect(editor.locator('ol li')).toContainText('Un bloque')
  await expect(page.getByRole('button', { name: 'Lista numerada', exact: true })).toHaveAttribute('aria-keyshortcuts', 'Control+Alt+7')
})
