import { promises as fs } from 'node:fs'
import { dirname } from 'node:path'
import { test, expect, chooseOpen, chooseSave } from './fixtures'
import { markdownProblem, markdownSignature } from '../src/shared/markdown'

const pixel = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF1cAAAAASUVORK5CYII=', 'base64')

test('validación GFM conserva casillas y alineación y bloquea contenido activo', () => {
  const source = '| A | B |\n| :--- | ---: |\n| ~~uno~~ | dos |\n\n- [ ] Pendiente\n- [x] Hecho\n\n![Foto](assets/foto.png "Título")\n'
  expect(markdownProblem(source)).toBeNull()
  expect(markdownSignature('- [ ] Tarea')).not.toBe(markdownSignature('- [x] Tarea'))
  expect(markdownSignature('| A |\n| :--- |')).not.toBe(markdownSignature('| A |\n| ---: |'))
  for (const source of ['[x](javascript:alert%281%29)', '![x](file:///C:/secret.png)', '<script>alert(1)</script>']) expect(markdownProblem(source)).not.toBeNull()
})

test('GFM abre, visualiza imagen relativa, edita casillas y conserva estructura al guardar y reabrir', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('formatos.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(testInfo.outputPath('pixel.png'), pixel)
  const source = '# Formatos\n\n| Nombre | Estado |\n| :--- | ---: |\n| Uno | ~~Antes~~ |\n\n- [ ] Pendiente\n- [x] Hecho\n\n![Pixel](pixel.png "Imagen local")\n\n[Referencia](https://example.com "Título")\n'
  await fs.writeFile(path, source)
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await expect(editor.locator('table')).toHaveCount(1)
  await expect(editor.locator('del')).toHaveText('Antes')
  await expect(editor.getByRole('checkbox')).toHaveCount(2)
  await expect(editor.getByRole('checkbox').nth(0)).not.toBeChecked()
  await expect(editor.getByRole('checkbox').nth(1)).toBeChecked()
  await expect.poll(() => editor.locator('img:not(.ProseMirror-separator)').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(1)
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  expect(await fs.readFile(path, 'utf8')).toBe(source)
  await editor.getByRole('checkbox').nth(0).check()
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  const saved = await fs.readFile(path, 'utf8')
  expect(markdownSignature(saved)).toBe(markdownSignature(source.replace('- [ ] Pendiente', '- [x] Pendiente')))
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(editor.getByRole('checkbox').nth(0)).toBeChecked()
  await expect(editor.locator('table')).toContainText('Uno')
  await page.screenshot({ path: testInfo.outputPath('gfm-wide.png') })
  await (await application.browserWindow(page)).evaluate(win => win.setSize(420, 700))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('gfm-narrow.png') })
})

test('tachado y listas de tareas se crean desde herramientas con historial', async ({ editorPage: page }) => {
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await editor.fill('Preparar entrega')
  await editor.press('Control+A')
  await page.getByRole('button', { name: 'Tachado', exact: true }).click()
  await expect(editor.locator('del')).toHaveText('Preparar entrega')
  await page.getByRole('button', { name: 'Lista de tareas', exact: true }).click()
  await expect(editor.getByRole('checkbox')).toHaveCount(1)
  await editor.getByRole('checkbox').check()
  await expect(editor.getByRole('checkbox')).toBeChecked()
  await page.getByRole('button', { name: 'Deshacer', exact: true }).click()
  await expect(editor.getByRole('checkbox')).not.toBeChecked()
  await page.getByRole('button', { name: 'Rehacer', exact: true }).click()
  await expect(editor.getByRole('checkbox')).toBeChecked()
})

test('tabla solo cabecera y tareas mixtas conservan datos al convertir y deshacer', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('bordes.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, '| Única |\n| --- |\n\n- [x] Completada\n- Normal\n')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await expect(editor.locator('table tr')).toHaveCount(1)
  await editor.locator('li').first().locator('p').click()
  await editor.press('Home')
  await editor.press('Control+Shift+End')
  await page.getByRole('button', { name: 'Lista de tareas', exact: true }).click()
  await expect(editor.getByRole('checkbox')).toHaveCount(2)
  await expect(editor.getByRole('checkbox').first()).toBeChecked()
  await expect(editor.getByRole('checkbox').last()).not.toBeChecked()
  await page.getByRole('button', { name: 'Deshacer', exact: true }).click()
  await expect(editor.getByRole('checkbox')).toHaveCount(1)
  await expect(editor.getByRole('checkbox')).toBeChecked()
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(editor.getByRole('checkbox')).toBeEnabled()
})

test('enlaces se insertan, editan y quitan conservando texto; cancelar devuelve foco', async ({ editorPage: page }) => {
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await editor.fill('Referencia')
  await editor.press('Control+A')
  await page.getByRole('button', { name: 'Enlace', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Dirección', { exact: true }).fill('https://example.com')
  await dialog.getByLabel('Texto', { exact: true }).fill('Referencia')
  await dialog.getByLabel('Título', { exact: true }).fill('Sitio de referencia')
  await dialog.getByRole('button', { name: 'Insertar', exact: true }).click()
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.com')
  await expect(editor).toBeFocused()
  await editor.locator('a').click()
  await page.getByRole('button', { name: 'Enlace', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Dirección', { exact: true }).fill('https://example.org/actualizado')
  await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await expect(editor.locator('a')).toHaveAttribute('href', 'https://example.org/actualizado')
  await editor.locator('a').click()
  await page.getByRole('button', { name: 'Enlace', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Quitar enlace', exact: true }).click()
  await expect(editor.locator('a')).toHaveCount(0)
  await expect(editor).toHaveText('Referencia')
  await page.getByRole('button', { name: 'Enlace', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Dirección', { exact: true }).fill('javascript:alert(1)')
  await page.getByRole('dialog').getByRole('button', { name: 'Insertar', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
  await page.keyboard.press('Control+O')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(editor).toBeFocused()
})

test('tabla se crea, modifica y guarda con filas y columnas', async ({ application, editorPage: page }, testInfo) => {
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await page.getByRole('button', { name: 'Tabla', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Filas', { exact: true }).fill('3')
  await dialog.getByLabel('Columnas', { exact: true }).fill('2')
  await dialog.getByRole('button', { name: 'Insertar', exact: true }).click()
  await expect(editor.locator('table tr')).toHaveCount(3)
  await expect(editor.locator('table tr').first().locator('th')).toHaveCount(2)
  await editor.locator('th').first().click()
  await page.keyboard.insertText('Nombre')
  await editor.locator('td').first().click()
  await page.keyboard.insertText('Dato')
  await page.getByRole('button', { name: 'Tabla', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Insertar fila después', exact: true }).click()
  await expect(editor.locator('table tr')).toHaveCount(4)
  const path = testInfo.outputPath('tabla.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await chooseSave(application, path)
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(path, 'utf8')).toContain('Dato')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(editor.locator('table tr')).toHaveCount(4)
  const tableAction = async (name: string) => {
    await page.getByRole('button', { name: 'Tabla', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name, exact: true }).click()
  }
  await editor.locator('td').first().click()
  await tableAction('Centrar')
  await expect(editor.locator('th').first()).toHaveCSS('text-align', 'center')
  await tableAction('Insertar columna después')
  await expect(editor.locator('table tr').first().locator('th')).toHaveCount(3)
  await tableAction('Eliminar columna')
  await expect(editor.locator('table tr').first().locator('th')).toHaveCount(2)
  await editor.locator('th').first().click()
  await tableAction('Eliminar fila')
  await expect(editor.locator('table tr')).toHaveCount(3)
  await expect(editor.locator('th').first()).toHaveText('Dato')
  await tableAction('Eliminar tabla')
  await expect(editor.locator('table')).toHaveCount(0)
  await page.getByRole('button', { name: 'Deshacer', exact: true }).click()
  await expect(editor.locator('table tr')).toHaveCount(3)
})

test('imágenes se insertan por URL, editan y eliminan sin perder su Markdown', async ({ application, editorPage: page }, testInfo) => {
  await page.route('https://images.example.test/**', route => route.fulfill({ contentType: 'image/png', body: pixel }))
  const editor = page.getByRole('textbox', { name: 'Documento Markdown' })
  await page.getByRole('button', { name: 'Imagen', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Origen', { exact: true }).fill('https://images.example.test/pixel.png')
  await dialog.getByLabel('Texto alternativo', { exact: true }).fill('Una imagen')
  await dialog.getByLabel('Título', { exact: true }).fill('Título de imagen')
  await dialog.getByRole('button', { name: 'Insertar', exact: true }).click()
  await expect(editor.locator('img:not(.ProseMirror-separator)')).toHaveAttribute('alt', 'Una imagen')
  await expect.poll(() => editor.locator('img:not(.ProseMirror-separator)').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(1)
  await editor.locator('img:not(.ProseMirror-separator)').click()
  await page.getByRole('button', { name: 'Imagen', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Texto alternativo', { exact: true }).fill('Imagen editada')
  await page.getByRole('dialog').getByRole('button', { name: 'Aplicar', exact: true }).click()
  await expect(editor.locator('img:not(.ProseMirror-separator)')).toHaveAttribute('alt', 'Imagen editada')
  const path = testInfo.outputPath('imagen.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await chooseSave(application, path)
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(path, 'utf8')).toContain('![Imagen editada](https://images.example.test/pixel.png "Título de imagen")')
  await editor.locator('img:not(.ProseMirror-separator)').click()
  await page.getByRole('button', { name: 'Imagen', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Quitar imagen', exact: true }).click()
  await expect(editor.locator('img:not(.ProseMirror-separator)')).toHaveCount(0)
  await page.getByRole('button', { name: 'Deshacer', exact: true }).click()
  await expect(editor.locator('img:not(.ProseMirror-separator)')).toHaveAttribute('alt', 'Imagen editada')
})

test('imágenes locales restringen lectura y actualizan su base al guardar como', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('original', 'nota.md')
  const copy = testInfo.outputPath('copia', 'nota.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.mkdir(dirname(copy), { recursive: true })
  await fs.writeFile(path, '![Local](pixel.png)\n')
  await fs.writeFile(testInfo.outputPath('original', 'pixel.png'), pixel)
  await fs.writeFile(testInfo.outputPath('fuera.png'), pixel)
  await fs.writeFile(testInfo.outputPath('original', 'falso.png'), '<script>active</script>')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  const img = page.getByRole('textbox', { name: 'Documento Markdown' }).locator('img:not(.ProseMirror-separator)')
  await expect.poll(() => img.evaluate((img: HTMLImageElement) => img.naturalWidth)).toBe(1)
  const values = await page.evaluate(async () => {
    const { id } = await window.documents.current()
    return Promise.all([
      window.documents.imageSource('otro-documento', 'pixel.png'),
      window.documents.imageSource(id, '../fuera.png'),
      window.documents.imageSource(id, '%2e%2e/fuera.png'),
      window.documents.imageSource(id, 'file:///C:/secret.png'),
      window.documents.imageSource(id, 'falso.png'),
      window.documents.imageSource(id, 'pixel.png')
    ])
  })
  expect(values.slice(0, 5)).toEqual([null, null, null, null, null])
  expect(values[5]).toMatch(/^data:image\/png;base64,/)
  await chooseSave(application, copy)
  await page.getByRole('button', { name: 'Guardar como', exact: true }).click()
  await expect.poll(() => page.evaluate(async () => {
    const { id } = await window.documents.current()
    return window.documents.imageSource(id, 'pixel.png')
  })).toBeNull()
  // A stale data URL would display the previous folder's image after Save As.
  await expect(img).not.toHaveAttribute('src')
})
