import { promises as fs } from 'node:fs'
import { dirname } from 'node:path'
import type { ElectronApplication, Page } from '@playwright/test'
import { test, expect, chooseOpen, chooseSave } from './fixtures'
import { markdownSignature, safeImage } from '../src/shared/markdown'

const pixel = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aF1cAAAAASUVORK5CYII=', 'base64')
const editor = (page: Page) => page.getByRole('textbox', { name: 'Documento Markdown' })
const images = (page: Page) => editor(page).locator('.document-image')
const button = (page: Page, name: string) => page.getByRole('button', { name, exact: true })
const conversionErrors = new WeakMap<Page, string[]>()
test.beforeEach(async ({ editorPage: page }) => {
  const errors: string[] = []
  conversionErrors.set(page, errors)
  page.on('console', message => {
    if (message.type() === 'error' && /milkdown|rangeerror|invalid content|parser|type of attribute|schema/i.test(message.text())) errors.push(message.text())
  })
})
test.afterEach(async ({ editorPage: page }) => { expect(conversionErrors.get(page)).toEqual([]) })
async function open(application: ElectronApplication, page: Page, path: string, source?: string) {
  if (source !== undefined) { await fs.mkdir(dirname(path), { recursive: true }); await fs.writeFile(path, source) }
  await chooseOpen(application, path)
  await button(page, 'Abrir').click()
  await expect(editor(page)).toBeVisible()
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
}
async function save(application: ElectronApplication, page: Page, path?: string) {
  if (path) { await fs.mkdir(dirname(path), { recursive: true }); await chooseSave(application, path) }
  await button(page, 'Guardar').click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
}
async function tableAction(page: Page, name: string) {
  await button(page, 'Tabla').click()
  await page.getByRole('dialog').getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}
async function createTable(page: Page, rows: number, columns: number) {
  await button(page, 'Tabla').click()
  await page.getByRole('dialog').getByLabel('Filas', { exact: true }).fill(String(rows))
  await page.getByRole('dialog').getByLabel('Columnas', { exact: true }).fill(String(columns))
  await page.getByRole('dialog').getByRole('button', { name: 'Insertar', exact: true }).click()
}
async function imageDialog(page: Page, index = 0) {
  await images(page).nth(index).click()
  await button(page, 'Imagen').click()
  await expect(page.getByRole('dialog').getByRole('heading')).toHaveText('Editar imagen')
  return page.getByRole('dialog')
}

test('auditor: dimensiones mínimas, máximas e inválidas de tabla', async ({ editorPage: page }) => {
  await button(page, 'Tabla').click()
  const dialog = page.getByRole('dialog')
  for (const [rows, columns] of [['0', '2'], ['21', '2'], ['2', '0'], ['2', '11'], ['1.5', '2']]) {
    await dialog.getByLabel('Filas', { exact: true }).fill(rows)
    await dialog.getByLabel('Columnas', { exact: true }).fill(columns)
    await dialog.getByRole('button', { name: 'Insertar', exact: true }).click()
    await expect(dialog).toBeVisible()
    await expect(editor(page).locator('table')).toHaveCount(0)
  }
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await createTable(page, 1, 1)
  await expect(editor(page).locator('tr')).toHaveCount(1)
  await expect(editor(page).locator('th')).toHaveCount(1)
  await tableAction(page, 'Eliminar fila')
  await expect(editor(page).locator('table')).toHaveCount(0)
  await createTable(page, 20, 10)
  await expect(editor(page).locator('tr')).toHaveCount(20)
  await expect(editor(page).locator('th, td')).toHaveCount(200)
})

test('auditor: cabecera única, pipes y marcas sobreviven edición, guardado y reapertura', async ({ application, editorPage: page }, info) => {
  const path = info.outputPath('inline.md')
  const source = '| **Fuerte** | *Énfasis* |\n| :--- | ---: |\n| `a\\|b` | ~~viejo~~ y [sitio](https://example.com) |\n\nFinal\n'
  await open(application, page, path, source)
  await expect(editor(page).locator('code')).toHaveText('a|b')
  await editor(page).locator('td').first().click()
  await tableAction(page, 'Insertar fila después')
  await tableAction(page, 'Eliminar fila')
  await save(application, page)
  expect(markdownSignature(await fs.readFile(path, 'utf8'))).toBe(markdownSignature(source))
  await open(application, page, path)
  await expect(editor(page).locator('strong')).toHaveText('Fuerte')
  await expect(editor(page).locator('em')).toHaveText('Énfasis')
  await expect(editor(page).locator('del')).toHaveText('viejo')
  await editor(page).locator('td').first().click()
  await tableAction(page, 'Eliminar fila')
  await expect(editor(page).locator('tr')).toHaveCount(1)
  await save(application, page)
  await open(application, page, path)
  await expect(editor(page).locator('tr')).toHaveCount(1)
})

test('auditor: filas y columnas antes/después conservan extremos y encabezado', async ({ application, editorPage: page }, info) => {
  await open(application, page, info.outputPath('edges.md'), '| H1 | H2 |\n| --- | --- |\n| A1 | A2 |\n| B1 | B2 |\n')
  const rows = editor(page).locator('tr')
  await editor(page).locator('th').first().click()
  await tableAction(page, 'Insertar fila antes')
  await expect(rows).toHaveCount(4)
  await expect(rows.nth(1)).toContainText('H1')
  await expect(rows.first().locator('th')).toHaveCount(2)
  await tableAction(page, 'Eliminar fila')
  await expect(rows.first()).toContainText('H1')
  await rows.last().locator('td').last().click()
  await tableAction(page, 'Insertar fila después')
  await expect(rows).toHaveCount(4)
  await tableAction(page, 'Eliminar fila')
  await expect(rows.last()).toContainText('B2')
  await editor(page).locator('th').first().click()
  await tableAction(page, 'Insertar columna antes')
  await expect(rows.first().locator('th')).toHaveCount(3)
  await expect(rows.first().locator('th').nth(1)).toHaveText('H1')
  await tableAction(page, 'Eliminar columna')
  await rows.last().locator('td').last().click()
  await tableAction(page, 'Insertar columna después')
  await expect(rows.last().locator('td')).toHaveCount(3)
  await tableAction(page, 'Eliminar columna')
  await expect(rows.last().locator('td')).toHaveText(['B1', 'B2'])
  await button(page, 'Deshacer').click()
  await expect(rows.last().locator('td')).toHaveCount(3)
  await button(page, 'Rehacer').click()
  await expect(rows.last().locator('td')).toHaveText(['B1', 'B2'])
})

test('auditor: alineación completa persiste y última columna se elimina con historial', async ({ application, editorPage: page }, info) => {
  const path = info.outputPath('alignment.md')
  await open(application, page, path, '| A | B | C |\n| --- | --- | --- |\n| 1 | 2 | 3 |\n')
  for (const [column, name, value] of [[0, 'Alinear a la izquierda', 'left'], [1, 'Centrar', 'center'], [2, 'Alinear a la derecha', 'right']] as const) {
    await editor(page).locator('td').nth(column).click()
    await tableAction(page, name)
    await expect(editor(page).locator('th').nth(column)).toHaveCSS('text-align', value)
    await expect(editor(page).locator('td').nth(column)).toHaveCSS('text-align', value)
  }
  await save(application, page)
  await open(application, page, path)
  for (const [column, value] of ['left', 'center', 'right'].entries()) await expect(editor(page).locator('td').nth(column)).toHaveCSS('text-align', value)
  await editor(page).locator('th').first().click()
  for (let index = 0; index < 3; index++) await tableAction(page, 'Eliminar columna')
  await expect(editor(page).locator('table')).toHaveCount(0)
  await button(page, 'Deshacer').click()
  await expect(editor(page).locator('th')).toHaveText('C')
  await button(page, 'Rehacer').click()
  await expect(editor(page).locator('table')).toHaveCount(0)
})

test('auditor: Tab y Shift Tab recorren celdas y Enter permite continuar fuera', async ({ editorPage: page }) => {
  await createTable(page, 2, 2)
  await page.keyboard.insertText('H1')
  await page.keyboard.press('Tab')
  await page.keyboard.insertText('H2')
  await page.keyboard.press('Tab')
  await page.keyboard.insertText('A1')
  await page.keyboard.press('Tab')
  await page.keyboard.insertText('A2')
  await expect(editor(page).locator('th')).toHaveText(['H1', 'H2'])
  await expect(editor(page).locator('td')).toHaveText(['A1', 'A2'])
  await page.keyboard.press('Shift+Tab')
  await page.keyboard.insertText('Reemplazo')
  await expect(editor(page).locator('td').first()).toContainText('Reemplazo')
  await editor(page).locator('td').last().click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('Después')
  await expect(editor(page).locator(':scope > p').last()).toHaveText('Después')
  await expect(editor(page).locator('td').last()).toHaveText('A2')
})

test('auditor: tabla de diez columnas es accesible a 420px sin desbordamiento global', async ({ application, editorPage: page }, info) => {
  const cells = Array.from({ length: 10 }, (_, i) => `Columna${i}TextoLargo`)
  await open(application, page, info.outputPath('wide.md'), `| ${cells.join(' | ')} |\n| ${cells.map(() => '---').join(' | ')} |\n| ${cells.join(' | ')} |\n`)
  await (await application.browserWindow(page)).evaluate(win => win.setSize(420, 740))
  await page.screenshot({ path: info.outputPath('wide-table-420.png') })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(editor(page).locator('th')).toHaveCount(10)
  const widths = await editor(page).locator('th').evaluateAll(cells => cells.map(cell => cell.getBoundingClientRect().width))
  expect(Math.min(...widths)).toBeGreaterThanOrEqual(40)
  await editor(page).locator('th').first().click()
  for (let column = 1; column < 10; column++) await page.keyboard.press('Tab')
  await page.keyboard.press('End')
  await page.keyboard.insertText(' accesible')
  await expect(editor(page).locator('th').last()).toHaveText('Columna9TextoLargo accesible')
  await page.getByRole('region', { name: 'Tabla con desplazamiento horizontal' }).hover()
  await page.mouse.wheel(2000, 0)
  await expect.poll(() => editor(page).locator('th').last().evaluate(cell => {
    const box = cell.getBoundingClientRect()
    const scrollport = cell.closest('[role="region"]')!.getBoundingClientRect()
    return box.left >= scrollport.left && box.right <= scrollport.right + 1
  })).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('wide-table-last-column-420.png') })
})

test('auditor: imagen sin alt ni título admite insertar, guardar, editar y quitar repetidamente', async ({ application, editorPage: page }, info) => {
  await page.route('https://audit.test/**', route => route.fulfill({ contentType: 'image/png', body: pixel }))
  await button(page, 'Imagen').click()
  await page.getByRole('dialog').getByLabel('Origen', { exact: true }).fill('https://audit.test/one.png')
  await page.getByRole('dialog').getByRole('button', { name: 'Insertar', exact: true }).click()
  await expect(images(page)).toHaveCount(1)
  const path = info.outputPath('image.md')
  await save(application, page, path)
  expect(await fs.readFile(path, 'utf8')).toContain('![](https://audit.test/one.png)')
  for (const alt of ['Primera edición', 'Segunda edición']) {
    const dialog = await imageDialog(page)
    await expect(dialog.getByLabel('Origen', { exact: true })).toHaveValue('https://audit.test/one.png')
    await dialog.getByLabel('Texto alternativo', { exact: true }).fill(alt)
    await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
    await save(application, page)
  }
  await open(application, page, path)
  const dialog = await imageDialog(page)
  await dialog.getByRole('button', { name: 'Quitar imagen', exact: true }).click()
  await expect(images(page)).toHaveCount(0)
  await button(page, 'Deshacer').click()
  await expect(images(page).locator('img')).toHaveAttribute('alt', 'Segunda edición')
  await button(page, 'Rehacer').click()
  await expect(images(page)).toHaveCount(0)
})

test('auditor: imagen rota conserva origen y permite reparación, eliminación e historial', async ({ application, editorPage: page }, info) => {
  await page.route('https://audit.test/missing.png', route => route.fulfill({ status: 404, body: '' }))
  await page.route('https://audit.test/fixed.png', route => route.fulfill({ contentType: 'image/png', body: pixel }))
  const path = info.outputPath('broken.md')
  await open(application, page, path, 'Antes ![No disponible](https://audit.test/missing.png) después\n')
  await expect(images(page).locator('.image-fallback')).toBeVisible()
  const dialog = await imageDialog(page)
  await expect(dialog.getByLabel('Origen', { exact: true })).toHaveValue('https://audit.test/missing.png')
  await dialog.getByLabel('Origen', { exact: true }).fill('https://audit.test/fixed.png')
  await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await expect.poll(() => images(page).locator('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(1)
  await save(application, page)
  expect(await fs.readFile(path, 'utf8')).toContain('Antes ![No disponible](https://audit.test/fixed.png) después')
  await button(page, 'Deshacer').click()
  await expect(images(page).locator('.image-fallback')).toBeVisible()
  await (await imageDialog(page)).getByRole('button', { name: 'Quitar imagen', exact: true }).click()
  await expect(editor(page)).toHaveText('Antes  después')
})

test('auditor: ruta relativa codificada cambia de base al guardar como sin modificar origen', async ({ application, editorPage: page }, info) => {
  const path = info.outputPath('original', 'nota.md'), copy = info.outputPath('copy', 'nota.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.mkdir(dirname(copy), { recursive: true })
  await fs.writeFile(info.outputPath('original', 'mi foto.png'), pixel)
  await open(application, page, path, '![](mi%20foto.png)\n')
  await expect.poll(() => images(page).locator('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(1)
  await chooseSave(application, copy)
  await button(page, 'Guardar como').click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await expect(images(page).locator('.image-fallback')).toBeVisible()
  expect(await fs.readFile(copy, 'utf8')).toBe('![](mi%20foto.png)\n')
  await expect((await imageDialog(page)).getByLabel('Origen', { exact: true })).toHaveValue('mi%20foto.png')
  await page.keyboard.press('Escape')
  await fs.writeFile(info.outputPath('copy', 'mi foto.png'), pixel)
  await open(application, page, copy)
  await expect.poll(() => images(page).locator('img').evaluate((image: HTMLImageElement) => image.naturalWidth)).toBe(1)
})

test('auditor: imagen dentro de enlace conserva vínculo al editarla', async ({ application, editorPage: page }, info) => {
  await page.route('https://audit.test/**', route => route.fulfill({ contentType: 'image/png', body: pixel }))
  const path = info.outputPath('linked.md')
  await open(application, page, path, '[![Foto](https://audit.test/photo.png)](https://example.com)\n')
  const dialog = await imageDialog(page)
  await dialog.getByLabel('Texto alternativo', { exact: true }).fill('Foto editada')
  await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await save(application, page)
  expect(markdownSignature(await fs.readFile(path, 'utf8'))).toBe(markdownSignature('[![Foto editada](https://audit.test/photo.png)](https://example.com)\n'))
})

test('auditor: imagen en celda conserva origen y marcas al modificar estructura', async ({ application, editorPage: page }, info) => {
  await page.route('https://audit.test/**', route => route.fulfill({ contentType: 'image/png', body: pixel }))
  const path = info.outputPath('image-in-table.md')
  const source = '| **Foto** | Detalle |\n| :---: | --- |\n| [![](https://audit.test/cell.png)](https://example.com) | a\\|b |\n'
  await open(application, page, path, source)
  await expect(images(page)).toHaveCount(1)
  await editor(page).locator('td').last().click()
  await tableAction(page, 'Insertar columna antes')
  await tableAction(page, 'Eliminar columna')
  await save(application, page)
  expect(markdownSignature(await fs.readFile(path, 'utf8'))).toBe(markdownSignature(source))
  await open(application, page, path)
  await expect(editor(page).locator('td').first().locator('a')).toHaveAttribute('href', 'https://example.com')
  await expect(editor(page).locator('td').last()).toHaveText('a|b')
  const dialog = await imageDialog(page)
  await expect(dialog.getByLabel('Origen', { exact: true })).toHaveValue('https://audit.test/cell.png')
  await dialog.getByRole('button', { name: 'Quitar imagen', exact: true }).click()
  await button(page, 'Deshacer').click()
  await expect(images(page)).toHaveCount(1)
})

test('auditor: orígenes peligrosos se rechazan en formulario y lector local', async ({ application, editorPage: page }, info) => {
  for (const value of ['javascript:alert(1)', 'data:image/svg+xml,<svg/>', 'file:///C:/secret.png', '//example.com/a.png', 'C:\\secret.png', '/etc/passwd', '%2fetc/passwd']) expect(safeImage(value)).toBe(false)
  await button(page, 'Imagen').click()
  for (const value of ['javascript:alert(1)', 'data:image/png;base64,aaaa', 'file:///C:/secret.png']) {
    await page.getByRole('dialog').getByLabel('Origen', { exact: true }).fill(value)
    await page.getByRole('dialog').getByRole('button', { name: 'Insertar', exact: true }).click()
    await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
    await expect(images(page)).toHaveCount(0)
  }
  await page.keyboard.press('Escape')
  await open(application, page, info.outputPath('safe', 'note.md'), 'Seguro\n')
  await fs.writeFile(info.outputPath('outside.png'), pixel)
  const results = await page.evaluate(async () => {
    const { id } = await window.documents.current()
    return Promise.all(['../outside.png', '%2e%2e/outside.png', '..%2foutside.png', 'file:///C:/secret.png', 'https://example.com/a.png'].map(source => window.documents.imageSource(id, source)))
  })
  expect(results).toEqual([null, null, null, null, 'https://example.com/a.png'])
})
