import { promises as fs } from 'node:fs'
import { dirname } from 'node:path'
import { maxDocumentBytes } from '../src/shared/documents'
import { test, expect, chooseChanges, chooseOpen, chooseSave } from './fixtures'

test('alternar vistas y formatos conserva bytes originales y estado guardado', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('original.md')
  const bytes = Buffer.from('\uFEFFTítulo\r\n======\r\n\r\nUn texto con __énfasis fuerte__.\r\n')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, bytes)
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Documento Markdown', exact: true }).locator('h1')).toHaveText('Título')
  for (let index = 0; index < 2; index++) {
    await page.getByRole('button', { name: 'Markdown', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Markdown', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('textbox', { name: 'Código Markdown', exact: true })).toBeVisible()
    expect(await page.getByRole('textbox', { name: 'Código Markdown', exact: true }).inputValue()).toContain('__énfasis fuerte__')
    await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Vista impresión', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('status')).toHaveText('Guardado')
  }
  await page.getByRole('button', { name: 'Formato de página', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Formato de página', exact: true })
  await dialog.getByRole('combobox', { name: 'Tamaño de papel', exact: true }).selectOption({ label: 'A5' })
  await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(path)).toEqual(bytes)
  expect(await page.evaluate(async () => (await window.documents.current()).dirty)).toBe(false)
})

test('ediciones Markdown y visuales se sincronizan y el guardado inmediato usa la última versión', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('ediciones.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await chooseSave(application, path)
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  await source.fill('# Última versión\n\n**Contenido recién editado**\n')
  await source.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(path, 'utf8')).toBe('# Última versión\n\n**Contenido recién editado**\n')
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Documento Markdown', exact: true })
  await expect(editor.locator('h1')).toHaveText('Última versión')
  await expect(editor.locator('strong')).toHaveText('Contenido recién editado')
  await editor.press('Control+End')
  await page.keyboard.insertText(' y revisión visual')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  await expect(source).toHaveValue(/y revisión visual/)
  await source.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(path, 'utf8')).toContain('y revisión visual')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(editor).toContainText('y revisión visual')
})

test('alternar vistas conserva el historial nativo de deshacer del código Markdown', async ({ editorPage: page }) => {
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  await source.fill('# Base\n')
  await source.press('Control+End')
  await page.keyboard.insertText('\nTexto agregado con teclado')
  await expect(source).toHaveValue('# Base\n\nTexto agregado con teclado')
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Documento Markdown', exact: true })).toContainText('Texto agregado con teclado')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  await source.press('Control+Z')
  await expect(source).toHaveValue('# Base\n')
})

test('deshacer la primera edición visual conserva el contenido guardado desde Markdown', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('frontera-historial.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, '\uFEFF# Base\r\n\r\nOriginal.\r\n')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  await source.press('Control+End')
  await page.keyboard.insertText('\nEdicion uno.\n')
  await source.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  const saved = '\uFEFF# Base\r\n\r\nOriginal.\r\n\r\nEdicion uno.\r\n'
  expect(await fs.readFile(path, 'utf8')).toBe(saved)
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Documento Markdown', exact: true })
  await editor.press('Control+End')
  await page.keyboard.insertText('Visual edit')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await editor.press('Control+Z')
  await expect(editor.locator('h1')).toHaveText('Base')
  await expect(editor.locator('p')).toHaveText(['Original.', 'Edicion uno.'])
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await expect.poll(() => page.evaluate(async () => (await window.documents.current()).dirty)).toBe(false)
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  await expect(source).toHaveValue('# Base\n\nOriginal.\n\nEdicion uno.\n')
  expect(await fs.readFile(path, 'utf8')).toBe(saved)
})

test('editar y guardar Markdown conserva BOM y CRLF sin marcar cambios pendientes falsos', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('crlf.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, '\uFEFF# Original\r\n\r\nTexto.\r\n')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  const changed = '# Editado\n\nContenido actualizado.\n'
  await source.fill(changed)
  await source.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(path, 'utf8')).toBe('\uFEFF# Editado\r\n\r\nContenido actualizado.\r\n')
  expect(await page.evaluate(async () => (await window.documents.current()).dirty)).toBe(false)
  await source.fill(`${changed}Cambio temporal.\n`)
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
  await source.fill(changed)
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await expect.poll(() => page.evaluate(async () => (await window.documents.current()).dirty)).toBe(false)
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Documento Markdown', exact: true }).locator('h1')).toHaveText('Editado')
  await expect(page.getByRole('status')).toHaveText('Guardado')
})

test('expansión de Markdown al límite no sustituye el borrador por una vista antigua', async ({ editorPage: page }) => {
  await page.getByRole('textbox', { name: 'Documento Markdown', exact: true }).fill('Versión visual anterior')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  const draft = 'a'.repeat(maxDocumentBytes)
  await source.fill(draft)
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(source).toBeVisible()
  expect(await source.inputValue() === draft).toBe(true)
  await expect(page.getByRole('alert')).toContainText('2 MB')
  await source.fill('# Recuperado\n')
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Documento Markdown', exact: true }).locator('h1')).toHaveText('Recuperado')
})

test('Markdown no admitido conserva el borrador y permite corregir sin guardar una versión antigua', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('recuperado.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await chooseSave(application, path)
  await page.getByRole('textbox', { name: 'Documento Markdown', exact: true }).fill('Versión anterior')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  const draft = '# Borrador pendiente\n\n<script>window.__unsafe = true</script>\n'
  await source.fill(draft)
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(source).toBeVisible()
  await expect(source).toHaveValue(draft)
  await expect(page.getByRole('alert')).toBeVisible()
  await source.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
  await expect(fs.stat(path)).rejects.toMatchObject({ code: 'ENOENT' })
  await expect(source).toHaveValue(draft)
  expect(await page.evaluate(() => '__unsafe' in window)).toBe(false)
  await source.fill('# Borrador corregido\n\nTodo sigue aquí.\n')
  await source.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(path, 'utf8')).toBe('# Borrador corregido\n\nTodo sigue aquí.\n')
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Documento Markdown', exact: true }).locator('h1')).toHaveText('Borrador corregido')
})

test('cancelar abrir conserva un borrador no admitido y descartarlo permite abrir otro archivo', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('otro.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, '# Otro documento\n')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  const draft = '# Mi borrador\n\n<div>Contenido conservado</div>\n'
  await source.fill(draft)
  await chooseOpen(application, path)
  await chooseChanges(application, 2)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(source).toHaveValue(draft)
  await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
  await chooseChanges(application, 1)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Documento Markdown', exact: true }).locator('h1')).toHaveText('Otro documento')
})

test('Día y Noche cambian interfaz, Markdown y ventana nativa manteniendo blanca la vista impresión', async ({ application, editorPage: page }, testInfo) => {
  const nativeWindow = await application.browserWindow(page)
  const rendered = page.getByRole('textbox', { name: 'Documento Markdown', exact: true })
  await rendered.fill('Documento con tema independiente')
  for (const [label, theme, nativeColor, rootColor, sourceColor] of [
    ['Día', 'day', '#ffffff', 'rgb(255, 255, 255)', 'rgb(32, 63, 93)'],
    ['Noche', 'night', '#183550', 'rgb(24, 53, 80)', 'rgb(237, 243, 248)']
  ]) {
    await page.getByRole('button', { name: label, exact: true }).click()
    await expect(page.getByRole('button', { name: label, exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    await expect(page.getByRole('main')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
    await expect(rendered).toHaveCSS('color', 'rgb(23, 45, 64)')
    expect((await nativeWindow.evaluate(win => win.getBackgroundColor())).toLowerCase()).toBe(nativeColor)
    await page.getByRole('button', { name: 'Markdown', exact: true }).click()
    await expect(page.locator('body')).toHaveCSS('background-color', rootColor)
    await expect(page.getByRole('textbox', { name: 'Código Markdown', exact: true })).toHaveCSS('color', sourceColor)
    await page.screenshot({ path: testInfo.outputPath(`markdown-${theme}.png`) })
    await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
    await expect(rendered).toHaveText('Documento con tema independiente')
    await expect(page.getByRole('status')).toHaveText('Cambios sin guardar')
    await page.screenshot({ path: testInfo.outputPath(`impresion-${theme}.png`) })
  }
  const invalid = await page.evaluate(async () => {
    try { await window.appearance.setTheme('invalid' as 'day'); return 'accepted' }
    catch { return 'rejected' }
  })
  expect(invalid).toBe('rejected')
  await expect(page.getByRole('button', { name: 'Noche', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect((await nativeWindow.evaluate(win => win.getBackgroundColor())).toLowerCase()).toBe('#183550')
})

test('el fondo de vista impresión es independiente del tema del sistema y no modifica el documento', async ({ application, editorPage: page }, testInfo) => {
  const path = testInfo.outputPath('fondo.md')
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, '# Fondo independiente\n\nTexto de lectura con **énfasis**.\n\n- Un elemento\n')
  await chooseOpen(application, path)
  await page.getByRole('button', { name: 'Abrir', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Documento Markdown', exact: true })
  await expect(page.getByRole('button', { name: 'Papel blanco', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Fondo noche', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Fondo noche', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('main')).toHaveCSS('background-color', 'rgb(24, 53, 80)')
  await expect(editor).toHaveCSS('color', 'rgb(237, 243, 248)')
  await page.getByRole('button', { name: 'Día', exact: true }).click()
  await expect(page.getByRole('main')).toHaveCSS('background-color', 'rgb(24, 53, 80)')
  await expect(editor).toHaveCSS('color', 'rgb(237, 243, 248)')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await page.screenshot({ path: testInfo.outputPath('sistema-dia-papel-noche.png') })
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  await expect(page.getByRole('group', { name: 'Fondo de vista impresión', exact: true })).toHaveCount(0)
  await expect(page.locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.getByRole('button', { name: 'Vista impresión', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Fondo noche', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Papel blanco', exact: true }).click()
  await expect(page.getByRole('main')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(editor).toHaveCSS('color', 'rgb(23, 45, 64)')
  await page.getByRole('button', { name: 'Noche', exact: true }).click()
  await expect(page.getByRole('main')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await page.evaluate(async () => (await window.documents.current()).dirty)).toBe(false)
  expect(await fs.readFile(path, 'utf8')).toBe('# Fondo independiente\n\nTexto de lectura con **énfasis**.\n\n- Un elemento\n')
})

test('formato personalizado valida límites y cancelar o Escape conservan la selección aplicada', async ({ application, editorPage: page }, testInfo) => {
  const trigger = page.getByRole('button', { name: 'Formato de página', exact: true })
  const dialog = page.getByRole('dialog', { name: 'Formato de página', exact: true })
  const paper = dialog.getByRole('combobox', { name: 'Tamaño de papel', exact: true })
  await trigger.click()
  await paper.selectOption({ label: 'A5' })
  await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await trigger.click()
  await paper.selectOption({ label: 'Personalizado' })
  await dialog.getByLabel('Ancho (mm)', { exact: true }).fill('49')
  await dialog.getByLabel('Alto (mm)', { exact: true }).fill('1001')
  await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Ancho (mm)', { exact: true }).fill('180.5')
  await dialog.getByLabel('Alto (mm)', { exact: true }).fill('240.5')
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(paper.locator('option:checked')).toHaveText('A5')
  await paper.selectOption({ label: 'Carta' })
  await page.keyboard.press('Escape')
  await trigger.click()
  await expect(paper.locator('option:checked')).toHaveText('A5')
  await paper.selectOption({ label: 'Personalizado' })
  await dialog.getByLabel('Ancho (mm)', { exact: true }).fill('180.5')
  await dialog.getByLabel('Alto (mm)', { exact: true }).fill('240.5')
  await dialog.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await trigger.click()
  await expect(paper.locator('option:checked')).toHaveText('Personalizado')
  await expect(dialog.getByLabel('Ancho (mm)', { exact: true })).toHaveValue('180.5')
  await expect(dialog.getByLabel('Alto (mm)', { exact: true })).toHaveValue('240.5')
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Sin cambios')
  await expect(page.getByRole('main')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.getByRole('textbox', { name: 'Documento Markdown', exact: true })).toHaveCSS('color', 'rgb(23, 45, 64)')
  await page.screenshot({ path: testInfo.outputPath('visual-wide.png') })
  await (await application.browserWindow(page)).evaluate(win => win.setSize(420, 700))
  await expect.poll(() => page.evaluate(() => innerWidth)).toBeLessThanOrEqual(420)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  for (const name of ['Markdown', 'Vista impresión', 'Formato de página', 'Imprimir', 'Día', 'Noche', 'Papel blanco', 'Fondo noche']) {
    const box = await page.getByRole('button', { name, exact: true }).boundingBox()
    expect(box).not.toBeNull()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(await page.evaluate(() => innerWidth))
  }
  await page.screenshot({ path: testInfo.outputPath('visual-narrow.png') })
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('markdown-narrow.png') })
})
