import { promises as fs } from 'node:fs'
import { join } from 'node:path'
import type { ElectronApplication, Page } from '@playwright/test'
import { test, expect, chooseOpen, chooseChanges } from './fixtures'

async function selectNotebook(application: ElectronApplication, page: Page, root: string) {
  await fs.mkdir(root, { recursive: true })
  await chooseOpen(application, root)
  expect(await page.evaluate(() => window.workspace.choose())).toEqual({ status: 'ok' })
  const snapshot = await page.evaluate(() => window.workspace.current())
  expect(snapshot).not.toBeNull()
  return snapshot!
}

test('crea carpetas vacías anidadas y una nota editable desde el árbol', async ({ application, editorPage: page }, testInfo) => {
  const root = testInfo.outputPath('cuaderno-nuevo')
  const initial = await selectNotebook(application, page, root)
  const originalDocument = await page.evaluate(() => window.documents.current())
  await page.getByRole('button', { name: 'Mostrar cuaderno', exact: true }).click()
  const sidebar = page.getByRole('complementary', { name: 'Notas del cuaderno' })
  await sidebar.getByRole('button', { name: 'Nueva carpeta', exact: true }).click()
  const folderForm = sidebar.getByRole('form', { name: 'Crear carpeta', exact: true })
  await expect(folderForm.getByRole('textbox', { name: 'Nombre', exact: true })).toBeFocused()
  await expect(folderForm.getByRole('combobox', { name: 'Carpeta de destino' })).toHaveValue(initial.id)
  await folderForm.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Clientes')
  await folderForm.getByRole('button', { name: 'Crear', exact: true }).click()
  await expect(folderForm).not.toBeVisible()
  await expect(sidebar.getByRole('button', { name: 'Carpeta: Clientes', exact: true })).toBeVisible()
  expect(await fs.readdir(join(root, 'Clientes'))).toEqual([])
  expect(await page.evaluate(() => window.documents.current())).toEqual(originalDocument)
  const withFolder = await page.evaluate(() => window.workspace.current())
  const parent = withFolder!.folders.find((folder) => folder.relativePath === 'Clientes')!
  expect(parent).toBeDefined()
  await sidebar.getByRole('button', { name: 'Carpeta: Clientes', exact: true }).click()
  await sidebar.getByRole('button', { name: 'Nueva carpeta', exact: true }).click()
  await expect(folderForm.getByRole('combobox', { name: 'Carpeta de destino' })).toHaveValue(parent.id)
  await folderForm.getByRole('textbox', { name: 'Nombre', exact: true }).fill('2026')
  await folderForm.getByRole('button', { name: 'Crear', exact: true }).click()
  await expect(sidebar.getByRole('button', { name: 'Carpeta: Clientes/2026', exact: true })).toBeVisible()
  expect(await fs.readdir(join(root, 'Clientes', '2026'))).toEqual([])
  const nested = (await page.evaluate(() => window.workspace.current()))!.folders.find((folder) => folder.relativePath === 'Clientes/2026')!
  await sidebar.getByRole('button', { name: 'Carpeta: Clientes/2026', exact: true }).click()
  await sidebar.getByRole('button', { name: 'Nueva nota .md', exact: true }).click()
  const noteForm = sidebar.getByRole('form', { name: 'Crear nota', exact: true })
  await expect(noteForm.getByRole('combobox', { name: 'Carpeta de destino' })).toHaveValue(nested.id)
  await noteForm.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Contrato')
  await noteForm.getByRole('button', { name: 'Crear', exact: true }).click()
  await expect(noteForm).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Guardar', exact: true })).toBeEnabled()
  const created = await page.evaluate(() => window.workspace.current())
  expect(created!.notes.map((note) => note.relativePath)).toEqual(['Clientes/2026/Contrato.md'])
  expect(created!.currentNoteId).toBe(created!.notes[0].id)
  expect(await fs.readFile(join(root, 'Clientes', '2026', 'Contrato.md'), 'utf8')).toBe('')
  await page.getByRole('button', { name: 'Markdown', exact: true }).click()
  const source = page.getByRole('textbox', { name: 'Código Markdown', exact: true })
  await source.fill('# Contrato\n\nPrimera versión.\n')
  await source.press('Control+S')
  await expect(page.getByRole('status')).toHaveText('Guardado')
  expect(await fs.readFile(join(root, 'Clientes', '2026', 'Contrato.md'), 'utf8')).toBe('# Contrato\n\nPrimera versión.\n')
})

test('cancelar no crea archivos y las notas nuevas confirman los cambios antes de crearse', async ({ application, editorPage: page }, testInfo) => {
  const root = testInfo.outputPath('creacion-cancelada')
  await fs.mkdir(root, { recursive: true })
  await fs.writeFile(join(root, 'original.md'), '# Original\n')
  const snapshot = await selectNotebook(application, page, root)
  expect(await page.evaluate((id) => window.workspace.open(id), snapshot.notes[0].id)).toEqual({ status: 'ok' })
  await page.getByRole('button', { name: 'Mostrar cuaderno', exact: true }).click()
  const sidebar = page.getByRole('complementary', { name: 'Notas del cuaderno' })
  await sidebar.getByRole('button', { name: 'Nueva carpeta', exact: true }).click()
  const form = sidebar.getByRole('form', { name: 'Crear carpeta', exact: true })
  await form.getByRole('textbox', { name: 'Nombre', exact: true }).fill('Nunca creada')
  await form.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(form).not.toBeVisible()
  expect(await fs.readdir(root)).toEqual(['original.md'])
  const editor = page.getByRole('textbox', { name: 'Documento Markdown', exact: true })
  await editor.fill('Cambios que no se deben perder')
  await chooseChanges(application, 2)
  expect(await page.evaluate((id) => window.workspace.create(id, 'Cancelada', 'note'), snapshot.id)).toEqual({ status: 'cancelled' })
  expect(await fs.readdir(root)).toEqual(['original.md'])
  await expect(editor).toHaveText('Cambios que no se deben perder')
  expect((await page.evaluate(() => window.documents.current())).dirty).toBe(true)
  expect(await page.evaluate((id) => window.workspace.create(id, 'Carpeta permitida', 'folder'), snapshot.id)).toEqual({ status: 'ok' })
  await expect(editor).toHaveText('Cambios que no se deben perder')
  expect((await page.evaluate(() => window.documents.current())).dirty).toBe(true)
  await chooseChanges(application, 0)
  expect(await page.evaluate((id) => window.workspace.create(id, 'Nueva.md', 'note'), snapshot.id)).toEqual({ status: 'ok' })
  expect(await fs.readFile(join(root, 'original.md'), 'utf8')).toContain('Cambios que no se deben perder')
  expect(await fs.readFile(join(root, 'Nueva.md'), 'utf8')).toBe('')
  expect(await fs.readdir(root)).not.toContain('Nueva.md.md')
  await expect(editor).toHaveText('')
  expect((await page.evaluate(() => window.documents.current())).name).toBe('Nueva.md')
})

test('crear rechaza nombres Windows inválidos y no sobrescribe notas ni carpetas existentes', async ({ application, editorPage: page }, testInfo) => {
  const root = testInfo.outputPath('nombres-seguros')
  await fs.mkdir(join(root, 'Existente'), { recursive: true })
  await fs.writeFile(join(root, 'nota.md'), '# Contenido protegido\n')
  const snapshot = await selectNotebook(application, page, root)
  for (const kind of ['folder', 'note'] as const) {
    for (const name of ['..', '.', 'a/b', 'a\\b', 'C:escape', 'con', 'NUL.md', 'COM1', 'LPT9.txt', 'invalido?', 'final.', 'final ']) {
      const result = await page.evaluate(({ id, name, kind }) => window.workspace.create(id, name, kind), { id: snapshot.id, name, kind })
      expect(result.status, `${kind}: ${name}`).toBe('error')
    }
  }
  expect((await page.evaluate((id) => window.workspace.create(id, 'NOTA.md', 'note'), snapshot.id)).status).toBe('error')
  expect((await page.evaluate((id) => window.workspace.create(id, 'Existente', 'folder'), snapshot.id)).status).toBe('error')
  expect(await fs.readFile(join(root, 'nota.md'), 'utf8')).toBe('# Contenido protegido\n')
  expect((await fs.readdir(root)).sort()).toEqual(['Existente', 'nota.md'])
  expect((await page.evaluate(() => window.workspace.current()))!.notes.map((note) => note.relativePath)).toEqual(['nota.md'])
})

test('crear aísla los IDs del cuaderno y rechaza padres convertidos en junctions', async ({ application, editorPage: page }, testInfo) => {
  const firstRoot = testInfo.outputPath('primer-cuaderno')
  const root = testInfo.outputPath('segundo-cuaderno')
  const outside = testInfo.outputPath('fuera')
  await fs.mkdir(join(firstRoot, 'carpeta'), { recursive: true })
  const first = await selectNotebook(application, page, firstRoot)
  await fs.mkdir(join(root, 'sub'), { recursive: true })
  await fs.mkdir(outside, { recursive: true })
  const snapshot = await selectNotebook(application, page, root)
  const before = await page.evaluate(() => window.documents.current())
  for (const parentId of [first.id, first.folders[0].id, '../fuera', root, outside]) {
    expect((await page.evaluate((id) => window.workspace.create(id, 'No crear', 'folder'), parentId)).status).toBe('error')
  }
  const replacedId = snapshot.folders.find((folder) => folder.relativePath === 'sub')!.id
  await fs.rmdir(join(root, 'sub'))
  await fs.symlink(outside, join(root, 'sub'), 'junction')
  for (const kind of ['folder', 'note'] as const) {
    expect((await page.evaluate(({ id, kind }) => window.workspace.create(id, 'No crear', kind), { id: replacedId, kind })).status).toBe('error')
  }
  expect(await fs.readdir(outside)).toEqual([])
  expect(await fs.readdir(join(firstRoot, 'carpeta'))).toEqual([])
  expect(await page.evaluate(() => window.documents.current())).toEqual(before)
})

test('formulario estrecho incluye destino en el ciclo de foco y Escape cancela antes de cerrar el panel', async ({ application, editorPage: page }, testInfo) => {
  const root = testInfo.outputPath('crear-estrecho')
  await fs.mkdir(join(root, 'Destino'), { recursive: true })
  const snapshot = await selectNotebook(application, page, root)
  const destination = snapshot.folders.find((folder) => folder.relativePath === 'Destino')!
  const nativeWindow = await application.browserWindow(page)
  await nativeWindow.evaluate((window) => window.setSize(420, 700))
  await expect.poll(() => page.evaluate(() => innerWidth)).toBeLessThanOrEqual(420)
  await page.getByRole('button', { name: 'Mostrar cuaderno', exact: true }).click()
  const sidebar = page.getByRole('complementary', { name: 'Notas del cuaderno' })
  await sidebar.getByRole('button', { name: 'Nueva nota .md', exact: true }).click()
  const form = sidebar.getByRole('form', { name: 'Crear nota', exact: true })
  const name = form.getByRole('textbox', { name: 'Nombre', exact: true })
  const parent = form.getByRole('combobox', { name: 'Carpeta de destino' })
  await expect(name).toBeFocused()
  await name.fill('Temporal')
  await parent.selectOption(destination.id)
  await name.fill('Nombre:inválido')
  await form.getByRole('button', { name: 'Crear', exact: true }).click()
  await expect(form.getByRole('alert')).toContainText('nombre')
  await expect(name).toHaveValue('Nombre:inválido')
  await expect(parent).toHaveValue(destination.id)
  await expect(name).toBeFocused()
  await name.fill('Temporal')
  await parent.focus()
  await page.keyboard.press('Tab')
  expect(await sidebar.evaluate((element) => element.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Shift+Tab')
  await expect(parent).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(form).not.toBeVisible()
  await expect(sidebar).toBeVisible()
  await expect(sidebar.getByRole('button', { name: 'Nueva nota .md', exact: true })).toBeFocused()
  expect(await fs.readdir(join(root, 'Destino'))).toEqual([])
  await page.keyboard.press('Escape')
  await expect(sidebar).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Mostrar cuaderno', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('insertar un enlace relativo desde la barra conecta notas al guardar', async ({ application, editorPage: page }, testInfo) => {
  const root = testInfo.outputPath('enlace-entre-notas')
  await fs.mkdir(join(root, 'sub'), { recursive: true })
  await fs.writeFile(join(root, 'origen.md'), 'Referencia\n')
  await fs.writeFile(join(root, 'sub', 'destino.md'), '# Destino\n')
  const snapshot = await selectNotebook(application, page, root)
  const origin = snapshot.notes.find((note) => note.relativePath === 'origen.md')!
  const target = snapshot.notes.find((note) => note.relativePath === 'sub/destino.md')!
  expect(snapshot.links).toEqual([])
  expect(await page.evaluate((id) => window.workspace.open(id), origin.id)).toEqual({ status: 'ok' })
  const editor = page.getByRole('textbox', { name: 'Documento Markdown', exact: true })
  await expect(editor).toHaveText('Referencia')
  await editor.press('Control+A')
  await page.getByRole('button', { name: 'Enlace', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('radio', { name: 'Dirección web o manual', exact: true }).check()
  await dialog.getByLabel('Dirección', { exact: true }).fill('sub/destino.md')
  await dialog.getByRole('button', { name: 'Insertar', exact: true }).click()
  await expect(editor.locator('a')).toHaveAttribute('href', 'sub/destino.md')
  await expect(editor.locator('a')).toHaveText('Referencia')
  await page.getByRole('button', { name: 'Guardar', exact: true }).click()
  await expect(page.getByRole('status')).toHaveText('Guardado')
  await expect(page.getByRole('button', { name: 'Guardar', exact: true })).toBeEnabled()
  expect(await fs.readFile(join(root, 'origen.md'), 'utf8')).toContain('[Referencia](sub/destino.md)')
  const after = await page.evaluate(() => window.workspace.current())
  expect(after!.id).toBe(snapshot.id)
  expect(after!.links).toEqual([{ source: origin.id, target: target.id }])
  expect(after!.currentNoteId).toBe(origin.id)
})
